spring:
  application:
    name: Benchmarker Data API
  config:
    import:
    - optional:configserver:https://bm-data-config.herokuapp.com/
  cloud:
    config:
      name: bm-data-api
      label: master
      username: shaddowuser
      password: H7T*$