spring:
  application:
    name: Benchmarker Data API
  config:
    import:
    - optional:configserver:https://bm-data-config.herokuapp.com/
  cloud:
    config:
      name: bm-data-api
      label: master
      username: shaddowuser
      password: H7T*$
---
spring:
  application:
    name: bm-data-service-admin
  config:
    activate:
      on-profile:
      - dev
    import:
    - optional:configserver:http://localhost:8081
  cloud:
    config:
      name: bm-data-api
      label: dev
      username: shaddowuser
      password: H7T*$      